Allow callers to track add/remove listeners
feross/render-media pull request #70
Opened 2019-08-12 16:18 UTC by ddumont

Something like this may help callers clean up listeners #32

2019-08-14 20:31 UTC, feross requested changes
You're missing a `return renderMedia` in the `append()` function.

---

But more generally, I think this approach is exposing too much of the implementation details to the user. We should just return a single function that, when called, removes and destroys all resources.

2019-08-14 20:31 UTC, feross commented on index.js
> +      try {
Why did you introduce a `try` here?

2019-08-14 20:31 UTC, feross commented on index.js
> +      try {
This is not how to handle errors. We already pass `err` into the callback.

2019-08-14 20:31 UTC, feross commented on index.js
> +        return useVideostream()
It's not ideal to return the `Videostream` instance in this case but to return nothing in the other cases. The user of this API will be very confused.

2019-08-14 20:31 UTC, feross commented on index.js
> +      return new Videostream(file, elem)
Why are you returning the `Videostream` instance?

2020-11-17 20:16 UTC, feross commented
@ddumont Are you interested in addressing the review feedback in this PR and helping get it over the finish line?>

2020-11-18 21:04 UTC, ddumont commented
I'd like to close this pr, I've since moved away from render-media.

2020-11-18 21:04 UTC, closed without merging